### ISSUE TITLE
windows does not build.

### ISSUE THREAD

**Issue by blademaster-888** [sentrionic/Horizon#1]
hi. just found your git repo and it's so cool! but... i couldn't get it to run. 

i tried using flutter lower than 3.0.5 but all gave me errors, then i try flutter 3.3.0 and they got rid of all errors for the flutter app.

but i stil get errors trying to build windows.

on the debug windows im seeing errors relating to libwinmedia - 0.0.3

cheers.

**Comment by sentrionic** [comment]
Can you paste the error? Did you select Windows as the build target? And do you have Flutter setup to build Windows applications?

**Comment by blademaster-888** [comment]
I have built windows app before for my apps so that's not the issue. the error is related to  libwinmedia - 0.0.3 which I believe is from the package ```just_audio_libwinmedia: ^0.0.4+1``` which is deprecated. they asked users to use just_audio_windows: 0.2.0 in place of that but it doesnt build and shows  no clear error: 

Launching lib\main.dart on Windows in debug mode...
Building Windows application...                                         
Exception: Build process failed.

**Comment by blademaster-888** [comment]
the flutter doctor shows no issues:

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.19044.2965], locale en-AU)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.3)   
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.78.2)      
[√] Connected device (3 available)
[√] HTTP Host Availability        

• No issues found!

**Comment by blademaster-888** [comment]
here is the full error when i put just_audio_libwindmedia package back:

Building on Windows against C++/WinRT 2.0.210806.1
C++ Standard: 17
Enabled Dart VM NativePorts callbacks.
D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.dir\Debug\Generated Files\winrt/impl/Windows.UI.Xaml.Media.Animation.0.h(2306,39): warning C4002: too many arguments for function-like macro invocation 'GetCurrentTime' [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(389,25): warning C4018: '<': signed/unsigned mismatch [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(539,25): warning C4018: '<': signed/unsigned mismatch [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(662,25): warning C4018: '<': signed/unsigned mismatch [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(810,10): warning C4244: 'return': conversion from '_Rep' to 'int32_t', possible loss of data [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]  
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(819,46): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]  
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(828,52): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]  
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(837,52): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]  
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(845,74): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]  
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1637,10): warning C4244: 'return': conversion from '_Rep' to 'int32_t', possible loss of data [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj] 
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1654,33): warning C4018: '<': signed/unsigned mismatch [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1661,33): warning C4018: '<': signed/unsigned mismatch [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1670,33): warning C4018: '<': signed/unsigned mismatch [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1677,33): warning C4018: '<': signed/unsigned mismatch [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1689,33): warning C4018: '<': signed/unsigned mismatch [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1650,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1651,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1652,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1658,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1665,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1667,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1674,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1681,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1683,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1684,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1685,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1686,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1687,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1693,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1695,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1709,33): warning C4018: '<': signed/unsigned mismatch [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1719,33): warning C4018: '<': signed/unsigned mismatch [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1733,33): warning C4018: '<': signed/unsigned mismatch [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1745,33): warning C4018: '<': signed/unsigned mismatch [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1707,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1713,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1715,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1717,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1723,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1727,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1728,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1729,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1737,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1739,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1740,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1741,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1742,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1743,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1749,3): warning C4996: 'strncpy': This fuD:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1751,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1773,58): warning C4244: 'argument': conversion from 'uint64_t' to 'uint32_t', possible loss of data [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1775,40): warning C4244: 'argument': conversion from 'uint64_t' to 'uint32_t', possible loss of data [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1326,1): warning C4244: '=': conversion from '_Rep' to 'int32_t', possible loss of data [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\d-code\GO-STUFF\Horizon\app\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1270,1): warning C4244: '=': conversion from '_Rep' to 'int32_t', possible loss of data [D:\d-code\GO-STUFF\Horizon\app\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
Building Windows application...
Exception: Build process failed.

**Comment by sentrionic** [comment]
I've updated the dependencies. Now it at least builds, I'm not sure if replacing the `just_audio_libwinmedia` with `just_audio_windows` broke something.

**Comment by blademaster-888** [comment]
what flutter sdk are you using? flutter 3.3.0 doesnt work. i'll try a higher one.

**Comment by sentrionic** [comment]
```
Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (6 weeks ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1
```

**Comment by blademaster-888** [comment]
it seems adding new flutter gave me lots of errors and found the solution to those errors was to add vsc to run admin and gitbash to run as admin.. 

and after all that i got no compile errors so i went and try to build it.

stil no luck. this is what i get with flutter 3712 stable

```
/d/d-code/GO-STUFF/horizon2/app$ flutter build windows

 Building with sound null safety 

Building Windows application...                                         
Build process failed.
```

my system:
amd ryzen 3600
windows 10 home
flutter 3712 stable
vsc latest and visual studio 2022 community latest
android studio latest

**Comment by sentrionic** [comment]
While I have Windows 11 and an Intel CPU, I doubt it would make much of a difference. Have you tried running it in debug? Have you also tried running `flutter clear` to remove the old dependencies?

**Comment by blademaster-888** [comment]
yes i tried both flutter build windows and via the debug. both not showing any errors... but build just failed. is there a way to show more debug logs/infos? 

yes. i do flutter clean everytime as i have many experience with this being the issues XD

and i agree with windows 10/11 not being the main problem here.

**Comment by sentrionic** [comment]
Usually the `Debug Console` tab in VSCode should show the error. I don't know any other way to print more info.

**Comment by blademaster-888** [comment]
this is what i get doing the flutter run -d windows (debug cmd way)

results are:
```
Launching lib\main.dart on Windows in debug mode...
Building Windows application...                                         
Exception: Build process failed.
```

**Comment by blademaster-888** [comment]
i will try to generate files again using:
flutter pub run build_runner watch --delete-conflicting-outputs

that generated fine:
[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 121ms

[INFO] Succeeded after 31.8s with 69 outputs (1120 actions)

but again it failed to build windows.

**Comment by blademaster-888** [comment]
I even went as far as disabling virtualization to off but.. no luck

**Comment by blademaster-888** [comment]
what is your visual studio version? i might have some updates left to do but i doubt it.

the old commit version at least generated the solution files for vs but this doesnt even give you that.

my visual studio version: 
 Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.3)

**Comment by sentrionic** [comment]
My VS version is 17.5.4 with the following components installed 
![image](https://github.com/sentrionic/Horizon/assets/38354571/b335d9ed-c5c3-4fc1-bad0-78657822239b)

**Comment by blademaster-888** [comment]
seems yours is slightly higher. i will try to update to that.

there is a problem to updating. it doesnt let me update to 17.5.4 but directly to 17.6.2

![image](https://github.com/sentrionic/Horizon/assets/1754262/ec5e48b6-648e-4deb-a8a1-2d9be05f8b70)

this might cause even more issues if i update that :/

**Comment by blademaster-888** [comment]
there seems to be 2 win 11 sdk checked.  maybe that might be the problem?

![image](https://github.com/sentrionic/Horizon/assets/1754262/9bf11121-d734-4431-81fb-8aa7bcefe405)

**Comment by sentrionic** [comment]
I only have the top one selected and no Windows 10 SDK. But you probably need one of them. in theory you should only need the stuff the `Desktop development with C++` auto selects for you.

**Comment by blademaster-888** [comment]
yes, originally i had only the top one but due to some blazor framework or the unreal engine 5.1 bug (can't remember what it was)  
so i added the 2nd one and that fixed it. but taking it out didnt solve the problem for this unfortunately.

**Comment by blademaster-888** [comment]
the working windows build i normally have so far only flutter 2.10.0 worked :/ on my personal project. but that is only 2.16.0 so i would prefer to use newer flutter versions for windows build but this isn't really beneficial at all lol. is your windows build really working? is it running?

**Comment by blademaster-888** [comment]
i will take the chance and update to latest vs. I appreciated your help in getting this working though :)

**Comment by sentrionic** [comment]
![image](https://github.com/sentrionic/Horizon/assets/38354571/b90390e8-f448-4da0-9996-1e5b8a86acb3)

**Comment by blademaster-888** [comment]
that is so awesome 🤤 ... wish i could get it to work

**Comment by blademaster-888** [comment]
can you add web support? it would be great to see where the problem lies betteen web and desktop builds.

**Comment by sentrionic** [comment]
Web support is not possible because `path_provider` does not support it.

**Comment by blademaster-888** [comment]
you can do a conditional foundation requirements for it to support web i think.

ok i somehow got the debug windows to get to this stage now:

error:

Exception has occurred.
PathNotFoundException (PathNotFoundException: Cannot create file, path = 'C:\Users\x\Documents\desktop-settings.hive' (OS Error: The system cannot find the file specified.
, errno = 2))

is there a reason why it can not create the path? seems it's not being able to write files

**Comment by sentrionic** [comment]
It should automatically generate those files on startup. And Documents also isn't a protected directory I think.

**Comment by blademaster-888** [comment]
hive works fine on flutter 2.10.0 though. i wonder why newer flutter isn't allowing that.

**Comment by sentrionic** [comment]
It also works on the current Flutter version since I had those files generated for me.

**Comment by blademaster-888** [comment]
this is what happened when i manually created that hive file XD

![image](https://github.com/sentrionic/Horizon/assets/1754262/9e78ae95-add8-467e-93d7-ddff9d73c2f4)

this is so weird. no errors but blank screen o.O

**Comment by blademaster-888** [comment]
ok so it wasnt no errors. 
i somehow found this error:

ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathNotFoundException: Cannot create file, path = 'C:\Users\x\Documents\desktop-settings.hive' (OS Error: The system cannot find the file specified.

which is odd because it should have found it hence it got past that point...

**Comment by sentrionic** [comment]
Running the app creates `desktop-settings.hive`,  `desktop-settings.lock`,  `hydrated_box.hive` and `hydrated_box.lock` for me.

**Comment by blademaster-888** [comment]
there is something weird about the flutters new security system. i think it's mixing administrator and users rights hence it's not having enough rights :/ i think this is a flutter issue so i'll look more into it. but i have a feeling if that's fixed, then i would be able to run this :) thank you so much for your time! I'll close this as solved as it is more relating to flutter than horizon :)
